name: containers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run_application_macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: make
      - test: make -C unit_test